run:
  deadline: 15m
  issues-exit-code: 1
  modules-download-mode: readonly
linters:
  disable-all: true
  enable:
    - deadcode
    - gas
    - goconst
    - gocyclo
    - gofmt
    - golint
    - ineffassign
    - interfacer
    - lll
    - maligned
    - megacheck
    - misspell
    - structcheck
    - unconvert
    - varcheck
